# Generated by Django 2.2.20 on 2021-09-04 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(default=None, max_length=200)),
                ('account_id', models.CharField(default=None, max_length=200)),
                ('name', models.CharField(default=None, max_length=200)),
                ('phone_number', models.CharField(default=None, max_length=200)),
                ('email_id', models.CharField(default=None, max_length=200)),
                ('adhaar_card', models.CharField(default=None, max_length=200)),
                ('pan_card', models.CharField(default=None, max_length=200)),
                ('address', models.CharField(default=None, max_length=400)),
                ('father_name', models.CharField(default=None, max_length=200)),
                ('mother_name', models.CharField(default=None, max_length=200)),
                ('date_of_birth', models.DateTimeField(default=None)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
